//----------------------------------------------------------------------------------------------------------------------
//	WinRTToolbox.idl			©2023 Stevo Brock		All rights reserved.
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
// MARK: WinRTToolbox namespace
namespace WinRTToolbox {

	//------------------------------------------------------------------------------------------------------------------
	// Delegates
	delegate	Double	DoubleProvider(Object sender, Object context);
	delegate	Object	ObjectProvider(Object sender, Object context);
	delegate	Single	SingleProvider(Object sender, Object context);
	delegate	String	StringProvider(Object sender, Object context);

	delegate	void	UInt32Handler(Object sender, UInt32 value);
	delegate	void	ObjectHandler(Object sender, Object object);
}
