//----------------------------------------------------------------------------------------------------------------------
//	WinRT Toolbox.idl			©2023 Stevo Brock		All rights reserved.
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
// MARK: WinRTToolbox namespace
namespace WinRTToolbox {

	//------------------------------------------------------------------------------------------------------------------
	// Delegates
	delegate	Double	DoubleProvider(Object sender, Object context);
	delegate	Object	ObjectProvider(Object sender, Object context);
	delegate	Single	FloatProvider(Object sender, Object context);
	delegate	String	StringProvider(Object sender, Object context);
}
